import type { jsPDF, TextOptionsLight } from 'jspdf';
import type { CellHookData, UserOptions } from 'jspdf-autotable';
import { containsArabicScript } from './pdf-bidi';

/**
 * Embeds and drives the Amiri font for /api/export-pdf's Arabic-capable
 * rendering, and drives jsPDF's own (correctly configured) bidi/shaping
 * pipeline for any string that contains Arabic script.
 *
 * jsPDF's built-in Helvetica has no Arabic glyphs at all, so without the
 * embedded font an Arabic label would render as tofu (missing-glyph boxes)
 * or be silently dropped. Every direct `doc.text(...)` call and every
 * autoTable cell in this route is *content*-gated on `containsArabicScript`,
 * never on the export's locale: an artisan can type an Arabic project or
 * material name in a French/English-locale export too, and a French/English
 * export's own catalog strings never contain Arabic script (see
 * pdf-catalog.ts) — so the correct rule is "does this specific string
 * contain Arabic script", not "is this export's locale ar". The base
 * document/table font stays plain Helvetica always; `drawContentAwareText`
 * and `arabicSafeCellHooks` below switch to Amiri only for the exact string
 * being drawn, and restore the prior font immediately after, so a `fr`/`en`
 * export with one Arabic-typed name doesn't leave the rest of the page in
 * the wrong font.
 *
 * See assets/fonts/amiri/SOURCE.md for the font's provenance and license,
 * and src/lib/exports/fonts/*.ts (generated by
 * scripts/generate-pdf-font-modules.mjs) for why the font ships as inlined
 * base64 JS modules rather than files read from disk at request time: that
 * makes each one an ordinary `import()`-able module, bundled exactly like
 * any other source module — no `process.cwd()`-relative filesystem read
 * that can break depending on where a serverless function's working
 * directory ends up, no dependency on the bundler's file-tracer noticing an
 * `fs` call, and no runtime network fetch. `registerAmiriFont` imports them
 * with a *dynamic* `import()`, not a static one, and the route only calls it
 * at all when the payload actually needs Arabic glyphs (see
 * `payloadNeedsArabicFont` below and its use in route.ts): a pure-Latin
 * fr/en export never pays to decode or embed the font at all, and Next can
 * split the ~1MB of base64 into a chunk that a pure-Latin request never
 * fetches.
 */

export const AMIRI_FONT_FAMILY = 'Amiri';

/** Matches assets/fonts/amiri/SOURCE.md; tests/pdf-fonts.test.js pins both to the actual file bytes. */
export const AMIRI_REGULAR_SHA256 = 'ab391c4147d054c48976e98322ad0eefe1427aa0e0502a12a4c75d80a70cfcd7';
export const AMIRI_BOLD_SHA256 = 'cfccb794268e7d573d857e6d6a67f89cf8a053e8ffd85dfa0c8ec1bb36fc4827';

export interface FontRegistration {
  ok: boolean;
}

/** A registration that was never attempted (the payload had no Arabic content to render). */
export const NOT_REGISTERED: FontRegistration = { ok: false };

/**
 * Registers the embedded Amiri regular+bold faces on `doc` under the
 * "Amiri" font family, so `doc.setFont('Amiri', 'normal'|'bold')` and the
 * cell hooks below can select real Arabic glyphs. Call this only when
 * `payloadNeedsArabicFont` is true (see route.ts) — never unconditionally.
 *
 * Never throws: a corrupted embedded font must degrade the PDF (Arabic text
 * falls back to whatever font was active before, typically tofu for the
 * Arabic portions but everything else still renders) rather than crash the
 * whole export. On failure it logs a generic message only — there is no
 * filesystem path to leak, since the font ships as bundled JS strings, not
 * files read at request time.
 */
export async function registerAmiriFont(doc: jsPDF): Promise<FontRegistration> {
  try {
    const [{ AMIRI_REGULAR_BASE64 }, { AMIRI_BOLD_BASE64 }] = await Promise.all([
      import('./fonts/amiri-regular-base64'),
      import('./fonts/amiri-bold-base64'),
    ]);
    doc.addFileToVFS('Amiri-Regular.ttf', AMIRI_REGULAR_BASE64);
    doc.addFont('Amiri-Regular.ttf', AMIRI_FONT_FAMILY, 'normal');
    doc.addFileToVFS('Amiri-Bold.ttf', AMIRI_BOLD_BASE64);
    doc.addFont('Amiri-Bold.ttf', AMIRI_FONT_FAMILY, 'bold');
    return { ok: true };
  } catch (error) {
    console.error(
      'registerAmiriFont: failed to register the embedded Arabic font;',
      'Arabic text in this export may render as missing glyphs.',
      error instanceof Error ? error.message : 'unknown error'
    );
    return { ok: false };
  }
}

/**
 * Whether this export's payload contains any Arabic-script text anywhere it
 * could actually be drawn — the free-typed `projectName`/`material` fields,
 * or the locale's own catalog (every `ar`-locale catalog string is Arabic;
 * `fr`/`en` never contain any, see pdf-catalog.ts). Every other field this
 * route draws is numeric/computed, never free text. Used once, up front in
 * route.ts, to decide whether registering (and therefore bundling) the
 * Amiri font is worth doing at all for this specific request.
 */
export function payloadNeedsArabicFont(locale: 'fr' | 'en' | 'ar', ...freeTextFields: string[]): boolean {
  return locale === 'ar' || freeTextFields.some(containsArabicScript);
}

// Unicode bidi formatting controls, by code point rather than as literal
// characters in a regex (a stray invisible control character pasted into
// source is impossible to spot-review): LRM/RLM (0x200E-0x200F), the
// LRE/RLE/PDF/LRO/RLO embedding/override family (0x202A-0x202E), and the
// LRI/RLI/FSI/PDI isolate family (0x2066-0x2069). These are zero-width by
// Unicode convention, but nothing guarantees an embedded font's renderer
// treats an unmapped Cf character as invisible rather than drawing a
// fallback (tofu) glyph -- so they are stripped rather than relied upon.
// Intl.DateTimeFormat inserts RLM marks around the day/month/year
// punctuation for `ar-MA` (see src/i18n/index.ts's INTL_LOCALES and
// formatDateTime); the digits and separators already read unambiguously
// left-to-right on their own, so nothing of value is lost by removing them.
function isBidiControlCodePoint(codePoint: number): boolean {
  return (
    codePoint === 0x200e ||
    codePoint === 0x200f ||
    (codePoint >= 0x202a && codePoint <= 0x202e) ||
    (codePoint >= 0x2066 && codePoint <= 0x2069)
  );
}

/** Removes invisible Unicode bidi control characters before a string reaches doc.text(...). */
export function stripBidiControls(text: string): string {
  return Array.from(text)
    .filter((ch) => !isBidiControlCodePoint(ch.codePointAt(0) ?? 0))
    .join('');
}

/**
 * The `doc.text(...)` options that make jsPDF's *own* bidi engine do the
 * right thing with a plain logical-order Arabic string: `isInputVisual:
 * false` tells it the string it's given (post-shaping — see the module doc
 * comment) is still in logical/reading order and needs reordering;
 * `isOutputVisual: true` tells it the result must be left-to-right drawing
 * order (jsPDF always draws characters at increasing x, so that's the only
 * order that displays correctly); `isSymmetricSwapping: true` mirrors
 * paired characters (parentheses, brackets) that sit inside the reordered
 * RTL span, so `"الأبعاد (cm)"` draws with the parentheses the right way
 * round instead of inverted. This exact combination was verified empirically
 * against a real generated PDF, re-parsed with pdfjs-dist and rendered with
 * @napi-rs/canvas (see tests/pdf-artifact.test.js) — every other combination
 * either leaves the text in logical (wrong reading direction) order or
 * mirrors the wrong things.
 *
 * Pass this on every `doc.text(...)` call whose text contains Arabic script,
 * with the RAW (unshaped, un-reordered) logical string — never pre-shape or
 * pre-reorder it yourself. jsPDF's own `preProcessText` event calls
 * `doc.processArabic()` (contextual letter-shaping) automatically, using the
 * correct logical-order neighbours; calling it a second time yourself before
 * handing the text to `doc.text` shapes it twice, which is exactly what
 * produced the old lam-alef double-shaping ligature artifact (see
 * pdf-bidi.ts's module doc comment).
 */
export const arabicBidiOptions = { isInputVisual: false, isOutputVisual: true, isSymmetricSwapping: true } as const;

/**
 * Draws `text` at `(x, y)`, switching to the embedded Amiri font for exactly
 * the duration of this one draw call if (and only if) `text` contains
 * Arabic script and `registration.ok` — then restores whatever font was
 * active before, so drawing one Arabic-containing label never leaks Amiri
 * into the next (Latin) label. This is the one path every direct
 * `doc.text(...)` call in the route should go through; see
 * `arabicSafeCellHooks` below for the equivalent for autoTable cells.
 */
export function drawContentAwareText(
  doc: jsPDF,
  registration: FontRegistration,
  text: string,
  x: number,
  y: number,
  options?: TextOptionsLight
): void {
  const clean = stripBidiControls(text);
  const isArabic = containsArabicScript(clean);
  const priorFont = isArabic && registration.ok ? doc.getFont() : null;
  if (priorFont) doc.setFont(AMIRI_FONT_FAMILY, priorFont.fontStyle);
  doc.text(clean, x, y, { ...options, ...(isArabic ? arabicBidiOptions : {}) });
  if (priorFont) doc.setFont(priorFont.fontName, priorFont.fontStyle);
}

interface CellTextStyles {
  halign?: 'left' | 'center' | 'right' | 'justify';
  valign?: 'top' | 'middle' | 'bottom';
}

/**
 * Draws every wrapped logical line of a cell label at the exact position
 * jspdf-autotable's own (internal, not part of its public API) cell-text
 * routine would use for the given halign/valign — see `arabicSafeCellHooks`
 * below for why this exists, and for where `lines` comes from (autoTable's
 * own already-wrapped `cell.text`, preserved before it gets blanked — never
 * re-wrapped here with different metrics).
 *
 * Each element of `lines` is a raw logical string; shaping and
 * bidi-reordering happen inside `doc.text` itself (see `arabicBidiOptions`),
 * so the halign math below measures each line's own *shaped* width
 * (`doc.processArabic(line)`, a pure, side-effect-free transform used only
 * for this measurement — it is never drawn) rather than the raw string's
 * width, since letter-joining can change a glyph's advance width, and two
 * lines of the same cell can shape to different widths. `y` is always the
 * position of the cell's *first* line (as `Cell.getTextPos()` returns it,
 * regardless of how many lines the cell holds — see its own source); every
 * subsequent line is stepped down by one `lineHeight`, and — for `valign`
 * `middle`/`bottom` — the whole block is shifted up first by the combined
 * height of every line, mirroring jspdf-autotable's own multi-line
 * `autoTableText` helper. A single-element `lines` array reproduces the
 * exact single-line geometry this function drew before it supported more
 * than one line.
 */
export function drawShapedCellText(doc: jsPDF, lines: string[], x: number, y: number, styles: CellTextStyles): void {
  const PHYSICAL_LINE_HEIGHT = 1.15;
  const fontSize = doc.internal.scaleFactor === 0 ? 0 : doc.getFontSize() / doc.internal.scaleFactor;
  const lineHeight = fontSize * doc.getLineHeightFactor();
  const lineCount = lines.length;

  let drawY = y + fontSize * (2 - PHYSICAL_LINE_HEIGHT);
  if (styles.valign === 'middle') drawY -= (lineCount / 2) * lineHeight;
  else if (styles.valign === 'bottom') drawY -= lineCount * lineHeight;

  for (const line of lines) {
    let drawX = x;
    if (styles.halign === 'center' || styles.halign === 'right') {
      const alignSize = fontSize * (styles.halign === 'center' ? 0.5 : 1);
      const shapedWidth = doc.getStringUnitWidth(doc.processArabic(line));
      drawX -= shapedWidth * alignSize;
    }
    doc.text(line, drawX, drawY, arabicBidiOptions);
    drawY += lineHeight;
  }
}

/**
 * jspdf-autotable calls `doc.text(cellText, x, y)` internally with no bidi
 * options at all (not part of its public API, verified against the
 * installed jspdf-autotable version) — which hits jsPDF's *default* bidi
 * behaviour, not the one Arabic content actually needs (see
 * `arabicBidiOptions`'s doc comment), and never switches font, so an Arabic
 * name would draw as tofu in whatever font the table's `styles.font` set
 * (Helvetica in every locale except a document explicitly using Amiri
 * throughout). So Arabic-containing cell content cannot go through
 * autoTable's own draw at all.
 *
 * These two hooks — spread into every `autoTable(doc, { ... })` call's
 * options as `{ willDrawCell: ..., didDrawCell: ... }` — intercept exactly
 * (and only) the cells whose raw content contains Arabic script:
 *  - `willDrawCell` fires after autoTable has already computed row
 *    heights/column widths *and wrapped the cell's text to fit the column*
 *    (`cell.text`, a `string[]` of one entry per wrapped logical line — see
 *    jspdf-autotable's own `Cell` — so blanking it here cannot under-size
 *    the row), immediately before it draws the cell's own text. Those
 *    already-wrapped lines are saved (keyed by the `Cell` instance itself,
 *    so a repeated header row — the *same* `Cell` object, redrawn once per
 *    page by autoTable, not a fresh one per page — still preserves the
 *    right lines for each page's own draw) before `cell.text = []` makes
 *    autoTable's own draw call `doc.text([], ...)`, which jsPDF treats as a
 *    no-op (empty-array early return) — suppressing its own (wrongly-shaped,
 *    wrong-font) draw entirely, without ever touching the cell's *color* to
 *    hide it. If `cell.text` is already empty here (defensively — should not
 *    normally happen, see the next bullet), the raw string itself is used as
 *    a single-line fallback rather than preserving nothing.
 *  - `didDrawCell` fires right after that (now-suppressed) draw. It draws
 *    every one of the preserved wrapped lines itself, in the correct font
 *    and shape/order, at the same position autoTable itself computed
 *    (`cell.getTextPos()`), in whatever ink color `cell.styles.textColor`
 *    already holds — the same color autoTable would have used, never
 *    overridden. It then *restores* `cell.text` to those same preserved
 *    lines (never leaves it blanked, and never deletes the map entry) so
 *    that a repeated header row's `Cell` instance still holds its real
 *    wrapped lines the next time `willDrawCell` runs for it on the
 *    following page — without this restore, page 2's `willDrawCell` would
 *    capture the `[]` this hook's own page-1 blank left behind, and page 2's
 *    header would draw nothing at all. A cell whose lines were never
 *    preserved, or were preserved as an empty array (both defensive-only —
 *    should not happen given the two paragraphs above), falls back to the
 *    cell's raw string as a single line.
 *
 * A cell with no Arabic content (almost every numeric/dimension cell, even
 * in an Arabic-locale export) is untouched by either hook — autoTable's own
 * draw is already correct for it.
 */
export function arabicSafeCellHooks(
  doc: jsPDF,
  registration: FontRegistration
): Pick<UserOptions, 'willDrawCell' | 'didDrawCell'> {
  // Bridges the two hooks for one specific draw of one specific cell — see
  // the doc comment above. Scoped to this one `arabicSafeCellHooks` call
  // (fresh per PDF render), not module-level state.
  const preservedLines = new WeakMap<CellHookData['cell'], string[]>();

  return {
    willDrawCell(data: CellHookData): void {
      const raw = data.cell.raw;
      if (typeof raw !== 'string' || !containsArabicScript(raw)) return;
      const wrapped = data.cell.text;
      preservedLines.set(data.cell, wrapped.length > 0 ? [...wrapped] : [raw]);
      data.cell.text = [];
    },
    didDrawCell(data: CellHookData): void {
      const raw = data.cell.raw;
      if (typeof raw !== 'string' || !containsArabicScript(raw)) return;
      const stored = preservedLines.get(data.cell);
      const lines = stored && stored.length > 0 ? stored : [raw];
      const pos = data.cell.getTextPos();
      const priorFont = registration.ok ? doc.getFont() : null;
      if (priorFont) doc.setFont(AMIRI_FONT_FAMILY, priorFont.fontStyle);
      drawShapedCellText(doc, lines.map(stripBidiControls), pos.x, pos.y, data.cell.styles);
      if (priorFont) doc.setFont(priorFont.fontName, priorFont.fontStyle);
      // Restore, rather than delete-and-leave-blank: see the didDrawCell
      // bullet above — a repeated header Cell instance needs real lines
      // here for its *next* page's willDrawCell to preserve.
      data.cell.text = lines;
    },
  };
}
